version: '3.7'
services:
  postgres:
    image: postgres:15.5-alpine
    container_name: postgres_${GIT_REF:-default}_database
    env_file:
      - dev-database.env
    ports:
      - "5432:5432"
    volumes:
      - ./dependencies/dev-init.sql:/docker-entrypoint-initdb.d/dev-database-volume/dev-init.sql
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
    name: database-${GIT_REF:-data}